[package]
name = "httpd2"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["journald"]
journald = ["slog-journald"]

[dependencies]
hyper = "0.13"
tokio = {version = "0.2", features = ["full"]}
futures = "0.3"
rustls = "0.16"
tokio-rustls = "0.12.2"
nix = "0.16.1"
clap = "2.33"
libc = "0.2.66"
tokio-util = "0.2.0"
bytes = "0.5.3"
httpdate = "0.3"
slog = "2"
slog-async = "2"
slog-term = "2"
slog-journald = {version = "2", optional = true}
structopt = "0.3.7"

[profile.release]
debug = 2
